import React from 'react';
import { JssProvider, SheetsRegistry, ThemeProvider } from 'react-jss';
import { shallow } from 'enzyme';
import theme from '../styles/theme';

/**
 *  JSS helper shallow
 * Wrapps the passed in component in Themeprovider and captures the styles generated
 * @param {React component} Component
 * @returns {Array} First item in array is the stylesheet
 * generated by jss, the second is the rendered component for further expects
 */
export default Component => {
  const sheets = new SheetsRegistry();
  const ClonedComponent = React.cloneElement(Component, { _renderid: 'rendered-component' });

  const tree = shallow(
    <JssProvider registry={sheets}>
      <ThemeProvider theme={theme}>{ClonedComponent}</ThemeProvider>
    </JssProvider>
  );
  return [
    sheets.toString(),
    tree.findWhere(node => node.props()._renderid === 'rendered-component')
  ];
};
